routes/web.php
<?php

Route::get('/', 'Commerce\HomeController');
Route::get('/category/{category}/{sub_category?}', 'Commerce\CategoryController');
Route::get('/search', 'Commerce\SearchController');
Route::resource('products', 'Commerce\ProductController');

//Route::resource('cart', 'Commerce\CartController');
Route::get('cart/clear', function () {
    Cart::clear();
    return redirect()->route('cart.index');
});
Route::resource('cart', 'Commerce\CartController');
// Route::get('cart', 'Commerce\CartController@index')->name('cart.index');
// Route::post('cart/{product}', 'Commerce\CartController@store')->name('cart.store');
// Route::patch('cart/{product}', 'Commerce\CartController@update')->name('cart.update');
// Route::delete('cart/{product}', 'Commerce\CartController@destroy')->name('cart.destroy');

Route::resource('checkout', 'Commerce\CheckoutController');

Auth::routes();
Route::redirect('admin', 'admin/dashboard');
Route::any('/admin/{any}', function() {
    return view('layouts.template');
})->where('any', '.*')->middleware('auth');

Route::get('/api/cart', function() {
    return \Cart::getContent();
});


Route::get('/api/cart/subtotal', function() {
    return \Cart::getSubTotal();
});

app/Http/Controllers/Commerce/CartController.php
<?php

namespace App\Http\Controllers\Commerce;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Inventory\Product;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('commerce.pages.cart');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = request()->product;
        // $duplicates = \Cart::search(function ($cartItem, $rowId) use ($product) {
        //     return $cartItem->id === $product->id;
        // });
    
        // if ($duplicates->isNotEmpty()) {
        //     return redirect()->route('cart.index')->with('success_message', 'Item is already in your cart!');
        // }

        \Cart::add($product['id'], $product['name'], $product['prices'][0]['pivot']['amount'], $request->quantity, $request->article);

        return \Cart::get($product['id']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = request()->validate([
            'quantity' => 'required|numeric|between:1,5'
        ]);

        // if ($data['quantity'] > $request->productQuantity) {
        //     session()->flash('errors', collect(['We currently do not have enough items in stock.']));
        //     return response()->json(['success' => false], 400);
        // }

        Cart::update($id, $request->quantity);
        session()->flash('success_message', 'Quantity was updated successfully!');
        return response()->json(['success' => true]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \Cart::remove($id);
        return response()->json('ready');
    }
}

app/Http/Controllers/Commerce/CategoryController.php
<?php

namespace App\Http\Controllers\Commerce;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Config\Category;
use App\Models\Config\SubCategory;

class CategoryController extends Controller
{
    public function __invoke($category, $sub_category = null)
    {
        $sub_category ? 
        $products = SubCategory::where('slug', $sub_category)->with('products')->first()
        : $products = Category::where('slug', $category)->with('products')->first();
        // dd($products->toArray());
        return view('commerce.pages.category')->withCategory($products);
    }
}

app/Http/Controllers/Commerce/CheckoutController.php
<?php

namespace App\Http\Controllers\Commerce;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\OrderProduct;
use App\Models\Inventory\Article;

class CheckoutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('commerce.pages.cart');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $content = \Cart::getContent()->map(function($item) {
            return "{$item->name}, {$item->quantity}";
        })->values()->toJson();

        $order = $this->addToOrdersTable($request, null);

        return $order;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    protected function addToOrdersTable($request, $error)
    {
        // Insert into orders table
        $order = Order::create([
            'user_id' => auth()->user() ? auth()->user()->id : null,
            'billing_email' => $request->billing_email,
            'billing_name' => "{$request->billing_first_name} {$request->billing_last_name}",
            'billing_address' => "{$request->billing_address_1} {$request->billing_address_2} ",
            'billing_city' => $request->billing_city,
            'billing_province' => $request->billing_state,
            'billing_postalcode' => $request->billing_postcode,
            'billing_phone' => $request->billing_phone,
            'billing_name_on_card' => $request->name_on_card ? $request->name_on_card : '',
            'billing_discount' => 0,
            'billing_discount_code' => 0,
            'billing_subtotal' => \Cart::getSubTotal(),
            'billing_tax' => 0,
            'billing_total' => \Cart::getTotal(),
            'error' => $error,
        ]);

        // Insert into order_product table
        foreach (\Cart::getContent() as $item) {
            OrderProduct::create([
                'order_id' => $order->id,
                'product_id' => $item->id,
                'article_id' => $item->attributes->id,
                'quantity' => $item->quantity,
            ]);
        }

        $this->decreaseQuantities();

        \Cart::clear();
        return redirect('checkout')->with('msg', 'Su orden fue procesada con exito');
    }

    protected function decreaseQuantities()
    {
        foreach (\Cart::getContent() as $item) {
            $article = Article::find($item->attributes->id);
            $article->update(['quantity_sold' => $article->quantity_sold + $item->quantity]);
        }
    }
}

app/Http/Controllers/Commerce/HomeController.php
<?php

namespace App\Http\Controllers\Commerce;

use App\Repositories\Products;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public $products;

    public function __construct()
    {
        $this->products = new Products;
    }

    public function __invoke()
    {
        return view('commerce.pages.home')
                ->with(
                    [
                        'suggestions' => $this->products->getSuggestions(),
                        'recients' => $this->products->getRecients()
                    ]
                );
    }
}

app/Http/Controllers/Commerce/ProductController.php
<?php

namespace App\Http\Controllers\Commerce;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Inventory\Product;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id)->load('imgs', 'prices', 'articles');
        return view('commerce.pages.single-product', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Commerce/SearchController.php
<?php

namespace App\Http\Controllers\Commerce;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Config\Category;
use App\Models\Inventory\Product;

class SearchController extends Controller
{
    public function __invoke()
    {
        $query = request('query');
        $products = Product::where('name', 'like', "%{$query}%")->get();//->with('products')->first();
        return view('commerce.pages.search')->withProducts( $products);
    }
}

resources/views/commerce/pages/cart.blade.php
@extends('commerce.layouts')

@section('content')
 <!-- Page Title -->
 <section class="page-title text-center">
    <div class="container">
      <h1 class=" heading page-title__title">checkout</h1>
    </div>
  </section> <!-- end page title -->

 @if (session('msg'))
   <div class="container">
     <div class="alert alert-success">
       {{ session('msg') }}
     </div>
   </div>
 @endif

  <!-- Checkout -->
  <section class="section-wrap checkout">
    <div class="container relative">
      <div class="row">

        <div class="ecommerce col">

          <div class="row mb-30">
            <div class="col-md-8">
              <p class="ecommerce-info">
                Returning Customer? 
                <a href="#" class="showlogin">Click here to login</a>
              </p>
            </div>
          </div>

          <form name="checkout" action="{{ route('checkout.store') }}" method="post" class="checkout ecommerce-checkout row">
            @csrf
            <div class="col-lg-7" id="customer_details">
              <div>
                <h2 class="uppercase mb-30">billing details</h2>

                <div class="row">
                  <div class="col-md-6">
                    <p class="form-row form-row-first validate-required ecommerce-invalid ecommerce-invalid-required-field" id="billing_first_name_field">
                      <label for="billing_first_name">First Name
                        <abbr class="required" title="required">*</abbr>
                      </label>
                      <input type="text" class="input-text" placeholder value name="billing_first_name" id="billing_first_name">
                    </p>
                  </div>
                  <div class="col-md-6">
                    <p class="form-row form-row-last validate-required ecommerce-invalid ecommerce-invalid-required-field" id="billing_last_name_field">
                      <label for="billing_last_name">Last Name
                        <abbr class="required" title="required">*</abbr>
                      </label>
                      <input type="text" class="input-text" placeholder value name="billing_last_name" id="billing_last_name">
                    </p>
                  </div> 
                </div> <!-- end name / last name -->

                <p class="form-row form-row-wide address-field validate-required ecommerce-invalid ecommerce-invalid-required-field" id="billing_address_1_field">
                  <label for="billing_address_1">Address
                    <abbr class="required" title="required">*</abbr>
                  </label>
                  <input type="text" class="input-text" placeholder="Street address" value name="billing_address_1" id="billing_address_1">
                </p>

                <p class="form-row form-row-wide address-field" id="billing_address_2_field">
                  <input type="text" class="input-text" placeholder="Apartment, suite, unit etc. (optional)" value name="billing_address_2" id="billing_address_2">
                </p>

                <p class="form-row form-row-wide address-field validate-required" id="billing_city_field" data-o_class="form-row form-row-wide address-field validate-required">
                  <label for="billing_city">Town / City
                    <abbr class="required" title="required">*</abbr>
                  </label>
                  <input type="text" class="input-text" placeholder="Town / City" value name="billing_city" id="billing_city">
                </p>

                <p class="form-row form-row-first address-field validate-state" id="billing_state_field" data-o_class="form-row form-row-first address-field validate-state">
                  <label for="billing_state">State / County</label>
                  <input type="text" class="input-text" placeholder value name="billing_state" id="billing_state">
                </p>

                <p class="form-row form-row-last address-field validate-required validate-postcode ecommerce-invalid ecommerce-invalid-required-field" id="billing_postcode_field" data-o_class="form-row form-row-last address-field validate-required validate-postcode">
                  <label for="billing_postcode">Postcode / ZIP
                    <abbr class="required" title="required">*</abbr>
                  </label>
                  <input type="text" class="input-text" placeholder value name="billing_postcode" id="billing_postcode">
                </p>

                <div class="row">
                  <div class="col-md-6">
                    <p class="form-row form-row-last validate-required validate-phone" id="billing_phone_field">
                      <label for="billing_phone">Phone
                        <abbr class="required" title="required">*</abbr>
                      </label>
                      <input type="text" class="input-text" placeholder value name="billing_phone" id="billing_phone">
                    </p>
                  </div>
                  <div class="col-md-6">
                    <p class="form-row form-row-first validate-required validate-email" id="billing_email_field">
                      <label for="billing_email">Email Address
                        <abbr class="required" title="required">*</abbr>
                      </label>
                      <input type="text" class="input-text" placeholder value name="billing_email" id="billing_email">
                    </p>
                  </div>
                </div>                      

              </div>

            </div> <!-- end col -->

            <!-- Your Order -->
            <div class="col-lg-5">
              <div class="order-review-wrap ecommerce-checkout-review-order" id="order_review">
                <h2 class="uppercase">Your Order</h2>
                <table class="table shop_table ecommerce-checkout-review-order-table">
                  <tbody>
                    @foreach(Cart::getContent() as $cart)
                    <tr>
                      <th>{{ $cart->name }}<span class="count"> x {{ $cart->quantity }}</span></th>
                      <td>
                        <span class="amount">${{ $cart->price * $cart->quantity }}</span>
                      </td>
                    </tr>
                    @endforeach

                    <tr class="cart-subtotal">
                      <th>Cart Subtotal</th>
                      <td>
                        <span class="amount">${{ Cart::getSubTotal() }}</span>
                      </td>
                    </tr>
                    <tr class="shipping">
                      <th>Shipping</th>
                      <td>
                        <span>Free Shipping</span>
                      </td>
                    </tr>
                    <tr class="order-total">
                      <th><strong>Total Amount</strong></th>
                      <td>
                        <strong><span class="amount">${{ Cart::getTotal() }}</span></strong>
                      </td>
                    </tr>
                  </tbody>
                </table>

                <div id="payment" class="ecommerce-checkout-payment">
                  <h2 class="uppercase">Payment Method</h2>
                  <ul class="payment_methods methods">

                    <li class="payment_method_bacs">
                      <input id="payment_method_bacs" type="radio" class="input-radio" name="payment_method" value="bacs" checked="checked">
                      <label for="payment_method_bacs">Credit Card</label>
                      <div class="payment_box payment_method_bacs">
                        formulario metodo de pago
                      </div>
                    </li>

                  </ul>
                  <div class="form-row place-order">
                    <input type="submit" name="ecommerce_checkout_place_order" class="btn btn-lg btn-color btn-button" id="place_order" value="Place order">
                  </div>
                </div>
              </div>
            </div> <!-- end order review -->
          </form>

        </div> <!-- end ecommerce -->

      </div> <!-- end row -->
    </div> <!-- end container -->
  </section> <!-- end checkout -->
@endsection

resources/views/commerce/pages/category.blade.php
@extends('commerce.layouts')

@section('content')
<section class="section-wrap pt-60 pb-30 catalog">
    <div class="container">
        @include('commerce.components.category.breadcrumbs')
        
        <div class="row">
            <div class="col-lg-9 order-lg-2 mb-40">
                @include('commerce.components.category.filters')
                <div class="row row-8">
                    @each('commerce.components.products.product', $category->products, 'item')
                    {{-- @include('commerce.components.products.product') --}}
                </div> 
                @include('commerce.components.category.pagination')
            </div>
            @include('commerce.components.category.sidebar')
        </div>
    </div>
</section>
@endsection

resources/views/commerce/pages/home.blade.php
@extends('commerce.layouts')
@section('content')
    @include('commerce.components.hero.hero')
    <div id="recient">
        @products(['products' => $recients])
        @slot('title', 'Reciente publicados')
        @endproducts
    </div>
    <div id="suggestion">
        @products(['products' => $suggestions])
        @slot('title', 'Recomendados')
        @endproducts
    </div>
@endsection

resources/views/commerce/pages/search.blade.php
@extends('commerce.layouts')

@section('content')
<section class="section-wrap pt-60 pb-30 catalog">
    <div class="container">
        @include('commerce.components.category.breadcrumbs')
        
        <div class="row">
            <div class="col-lg-9 order-lg-2 mb-40">
                @include('commerce.components.category.filters')
                <div class="row row-8">
                    @each('commerce.components.products.product', $products, 'item')
                    {{-- @include('commerce.components.products.product') --}}
                </div> 
                @include('commerce.components.category.pagination')
            </div>
            @include('commerce.components.category.sidebar')
        </div>
    </div>
</section>
@endsection

resources/views/commerce/pages/single-product.blade.php
@extends('commerce.layouts')

@section('content')
 <!-- Single Product -->
 <section class="section-wrap pb-20 product-single">
    <div class="container">

      <!-- Breadcrumbs -->
      <ol class="breadcrumbs">
        <li>
          <a href="index.html">Home</a>
        </li>
        <li>
          <a href="index.html">Women</a>
        </li>
        <li class="active">
          {{ $product->name }}
        </li>
      </ol>

      <div class="row">

        <div class="col-md-6 product-slider mb-50">

          <div class="flickity flickity-slider-wrap mfp-hover" id="gallery-main">
            @foreach($product->imgs as $img)
            <div class="gallery-cell">
              <a href="/storage{{ $img->url }}" class="lightbox-img">
                <img src="/storage{{ $img->url }}" alt="" />
              </a>
            </div>
            @endforeach
          </div> <!-- end gallery main -->

          <div class="gallery-thumbs" id="gallery-thumbs">
            @foreach($product->imgs as $img)
            <div class="gallery-cell">
              <img src="/storage{{ $img->url }}" alt="" />
            </div>
            @endforeach
          </div> <!-- end gallery thumbs -->

        </div> <!-- end col img slider -->

        <div class="col-md-6 product-single">
          <h1 class="product-single__title uppercase">{{ $product->name }}</h1>

          {{-- <div class="rating">
            <a href="#">3 Reviews</a>
          </div> --}}

          <span class="product-single__price">
            <ins>
              <span class="amount">${{ $product->prices[0]->pivot->amount }}</span>
            </ins>
            <del>
              {{-- <span>$30.00</span> --}}
            </del>
          </span>            

          <div class="colors clearfix">
            <span class="colors__label">Compartir 
              {{-- <span class="colors__label-selected">Fadaed Blue</span> --}}
            </span>
            <a href="whatsapp://send?text={{ url("/products/{$product->id}") }}" class="">
              <img src="https://cdn.icon-icons.com/icons2/840/PNG/512/Whatsapp_icon-icons.com_66931.png" alt="" width="50">
            </a>
            <a href="https://www.facebook.com/sharer/sharer.php?u={{ url("/products/{$product->id}") }}" class="">
              <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Facebook_Logo_%282019%29.png/600px-Facebook_Logo_%282019%29.png" alt="" width="38">
            </a>            
            <span class="colors__label">Colors 
              {{-- <span class="colors__label-selected">Fadaed Blue</span> --}}
            </span>
            @foreach ($product->colors as $color)
              <a href="#" class="colors__item colors__item--selected" style="background: {{ $color->hex }}"></a>
            @endforeach
          </div>
          <form-add-cart :product='{{ $product }}'></form-add-cart>
          <div class="product_meta">
            <ul>
              <li>
                <span class="product-code">Product Code:  <span>{{ $product->reference }}</span></span>
              </li>
              <li>
                <span class="product-material">Material: <span>{{ $product->material }}</span></span>
              </li>
              <li>
                <span class="product-country">Country: <span>Made in {{ $product->country }}</span></span>
              </li>
            </ul>                              
          </div>

          <!-- Accordion -->
          <div class="accordion mb-50" id="accordion">
            <div class="accordion__panel">
              <div class="accordion__heading" id="headingOne">
                <a data-toggle="collapse" href="#collapseOne" class="accordion__link accordion--is-open" aria-expanded="true" aria-controls="collapseOne">Description<span class="accordion__toggle">&nbsp;</span>
                </a>
              </div>
              <div id="collapseOne" class="collapse show" data-parent="#accordion" role="tabpanel" aria-labelledby="headingOne">
                <div class="accordion__body">
                  {{ $product->description }}
                </div>
              </div>
            </div>

            <div class="accordion__panel">
              <div class="accordion__heading" id="headingTwo">
                <a data-toggle="collapse" href="#collapseTwo" class="accordion__link accordion--is-closed" aria-expanded="false" aria-controls="collapseTwo">Information<span class="accordion__toggle">&nbsp;</span>
                </a>
              </div>
              <div id="collapseTwo" class="collapse" data-parent="#accordion" role="tabpanel" aria-labelledby="headingTwo">
                <div class="accordion__body">
                  <table class="table shop_attributes">
                    <tbody>
                      <tr>
                        <th>Size:</th>
                        <td>EU 41 (US 8), EU 42 (US 9), EU 43 (US 10), EU 45 (US 12)</td>
                      </tr>
                      <tr>
                        <th>Colors:</th>
                        <td>
                          @foreach ($product->colors as $color)
                              {{ $color->description }},
                          @endforeach
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            {{-- <div class="accordion__panel">
              <div class="accordion__heading" id="headingThree">
                <a data-toggle="collapse" href="#collapseThree" class="accordion__link accordion--is-closed" aria-expanded="false" aria-controls="collapseThree">Reviews<span class="accordion__toggle">&nbsp;</span>
                </a>
              </div>
              <div id="collapseThree" class="collapse" data-parent="#accordion" role="tabpanel" aria-labelledby="headingThree">
                <div class="accordion__body">
                  <div class="reviews">
                    <ul class="reviews__list">
                      <li class="reviews__list-item">
                        <div class="reviews__body">
                          <div class="reviews__content">
                            <p class="reviews__author"><strong>Alexander Samokhin</strong> - May 6, 2017 at 12:48 pm</p>
                            <div class="rating">
                              <a href="#"></a>
                            </div>
                            <p>This template is so awesome. I didn’t expect so many features inside. E-commerce pages are very useful, you can launch your online store in few seconds. I will rate 5 stars.</p>
                          </div>
                        </div>
                      </li>

                      <li class="reviews__list-item">
                        <div class="reviews__body">
                          <div class="reviews__content">
                            <p class="reviews__author"><strong>Christopher Robins</strong> - May 7, 2014 at 12:48 pm</p>
                            <div class="rating">
                              <a href="#"></a>
                            </div>
                            <p>This template is so awesome. I didn’t expect so many features inside. E-commerce pages are very useful, you can launch your online store in few seconds. I will rate 5 stars.</p>
                          </div>
                        </div>
                      </li>

                    </ul>         
                  </div> <!--  end reviews -->
                </div>
              </div>
            </div> --}}
          </div> <!-- end accordion -->

        </div> <!-- end col product description -->
      </div> <!-- end row -->
     
    </div> <!-- end container -->
  </section> <!-- end single product -->
@endsection